### ISSUE TITLE
Channel launch todo

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/46elks#1]
- [x] Code Review
- [x] Add @larsemil as repo admin
- [x] Add to website
- [x] Create packagist package
- [x] Add badges

**Comment by atymic** [comment]
Sorry for the delay @larsemil 

Is this ready to go? If so, i'll add to packagist and the website.

**Comment by larsemil** [comment]
We have a go. I repeat, we have a go!

**Comment by atymic** [comment]
Should be good to go. I've activated packagist & travis :)

**Comment by atymic** [comment]
You can tag the first release when you are ready.
